version: '3'
services:
  mynotes:
     image: mynotes
     build:
       context: ./
       dockerfile: Dockerfile
     ports:
       - 8080:8080
     volumes:
       - /data/myNotes-app

  client:
     image: client
     build:
       context: ./client/
       dockerfile: Dockerfile
     ports:
        - 3000:3000
     depends_on:
       - mynotes
     command: npm start