version: '3'
services:
  server:
     image: mynotes
     build:
       context: ./
       dockerfile: Dockerfile
     ports:
       - 8080:8080
     volumes:
       - /data/myNotes-app

  server2:
     image: mynotes
     build:
        context: ./
        dockerfile: Dockerfile
     volumes:
        - /data/myNotes-app


  loadbalancer:
      build: ./loadBalancer
      links:
        - server
        - server2


  client:
     image: client
     build:
       context: ./client/
       dockerfile: Dockerfile
     ports:
        - 3000:3000
     depends_on:
       - server
     command: npm start